# Project information
site_name: 'Accompanist'
site_description: 'A group of libraries to help write Jetpack Compose apps.'
site_author: 'Chris Banes'
site_url: 'https://chrisbanes.github.io/accompanist/'
remote_branch: gh-pages

docs_dir: docs-gen

# Repository
repo_name: 'Accompanist'
repo_url: 'https://github.com/chrisbanes/accompanist'

# Navigation
nav:
  - 'Overview': index.md
  - 'Coil': coil.md
  - 'Glide': glide.md
  - 'Picasso': picasso.md
  - 'API':
    - 'Coil': api/coil/index.md
    - 'Glide': api/glide/index.md
    - 'Picasso': api/picasso/index.md
    - 'Image Loading Core': api/imageloading-core/index.md
  - 'Snapshots': using-snapshot-version.md
  - 'Contributing': contributing.md
  - 'Maintainers':
    - 'Update guide': updating.md

# Configuration
theme:
  name: 'material'
  language: 'en'
  icon:
    logo: material/music-clef-treble
  palette:
    primary: 'black'
    accent: 'deep orange'
  font:
    text: 'IBM Plex Sans'
    code: 'IBM Plex Mono'

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - footnotes
  - toc:
      permalink: true
  - pymdownx.betterem
  - pymdownx.superfences

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/chrisbanes