# Project information
site_name: 'Accompanist'
site_description: 'A group of libraries to help write Jetpack Compose apps.'
site_author: 'Google'
site_url: 'https://google.github.io/accompanist/'
edit_uri: 'tree/main/docs/'
remote_branch: gh-pages

docs_dir: docs-gen

# Repository
repo_name: 'Accompanist'
repo_url: 'https://github.com/google/accompanist'

# Navigation
nav:
  - 'Overview': index.md
  - 'Insets':
    - 'Guide': insets.md
    - 'API': api/insets/
  - 'System UI Controller':
    - 'Guide': systemuicontroller.md
    - 'API': api/systemuicontroller/
  - 'AppCompat Theme Adapter':
    - 'Guide': themeadapter-appcompat.md
    - 'API': api/themeadapter-appcompat/
  - 'Material Theme Adapter':
    - 'Guide': themeadapter-material.md
    - 'API': api/themeadapter-material/
  - 'Material 3 Theme Adapter':
    - 'Guide': themeadapter-material3.md
    - 'API': api/themeadapter-material3/
  - 'Core Theme Adapter':
    - 'Guide': themeadapter-core.md
    - 'API': api/themeadapter-core/
  - 'Pager layouts':
    - 'Guide': pager.md
    - 'API': api/pager/
  - 'Swipe Refresh':
    - 'Guide': swiperefresh.md
    - 'API': api/swiperefresh/
  - 'Placeholder':
    - 'Guide': placeholder.md
    - 'Foundation API': api/placeholder/
    - 'Material API': api/placeholder-material/
  - 'Drawable Painter':
    - 'Guide': drawablepainter.md
    - 'API': api/drawablepainter/ 
  - 'Flow layouts':
    - 'Guide': flowlayout.md
    - 'API': api/flowlayout/
  - 'Permissions':
    - 'Guide': permissions.md
    - 'API': api/permissions/
  - 'Navigation Animation':
      - 'Guide': navigation-animation.md
      - 'API': api/navigation-animation/
  - 'Navigation Material':
      - 'Guide': navigation-material.md
      - 'API': api/navigation-material/
  - 'WebView':
      - 'Guide': web.md
      - 'API': api/web/
  - 'Adaptive':
      - 'Guide': adaptive.md
      - 'API': api/adaptive
  - 'Test Harness':
      - 'Guide': testharness.md
      - 'API': api/testharness
  - 'Snapshots': using-snapshot-version.md
  - 'Contributing': contributing.md
  - 'Maintainers':
    - 'Update guide': updating.md

# Configuration
theme:
  name: 'material'
  language: 'en'
  icon:
    logo: material/music-clef-treble
  palette:
    primary: 'black'
    accent: 'deep orange'
  font:
    text: 'Roboto'
    code: 'JetBrains Mono'

# Extensions
markdown_extensions:
  - admonition
  - attr_list
  - codehilite:
      guess_lang: false
  - footnotes
  - toc:
      permalink: true
  - pymdownx.betterem
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.details
